-- Migration: raffle_schema
-- Created at: 2026-08-19T01:52:29.653Z
-- Generated by meoo db migrate

CREATE TABLE raffle_config (id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1), prizes jsonb NOT NULL DEFAULT '["口红","包","花"]'::jsonb, redemption_text text NOT NULL DEFAULT '请找百度最帅的人兑奖', updated_at timestamptz NOT NULL DEFAULT now()); INSERT INTO raffle_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING; CREATE TABLE raffle_history (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, phone text NOT NULL, prize text NOT NULL, created_at timestamptz NOT NULL DEFAULT now()); ALTER TABLE raffle_config ENABLE ROW LEVEL SECURITY; ALTER TABLE raffle_history ENABLE ROW LEVEL SECURITY;
